# Generated by Django 5.2.7 on 2025-11-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='preco',
        ),
        migrations.AddField(
            model_name='produto',
            name='altura',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='largura',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='material',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='peso',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
