# Generated by Django 5.2.7 on 2025-11-06 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_categoria_nome_alter_produto_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagem_principal',
        ),
    ]
